### ISSUE TITLE
Placeholder: %Bank_[gamemode]_island_balance_number%

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/Bank#13]
**Description**
Hello,

Can you add a placeholder withe juste the numbers when we call the placeholder `%Bank_bskyblock_island_balance%`

Ex: If I call this placeholder I have this 12,500.00€ can you change this placeholder or create a new placeholder for have just the number like this 12500  ?

**Placeholder**: `%Bank_[gamemode]_island_balance_number%`

Thank you very much, this placeholder is very important for me when we create some conditions

**Comment by tastybento** [comment]
Done in https://github.com/BentoBoxWorld/Bank/commit/393332991c38931b33a50339c118f27fb17be1d1

Note that the value may be in scientific notation depending on how large the balance is.
