### ISSUE TITLE
Island Money Balance

### ISSUE THREAD

**Issue by Tina-King** [BentoBoxWorld/Bank#2]
#### Is your feature request related to a problem?

In Skyblock specifically, the goal is becoming the /is top and /baltop (Basically being the biggest and the best). A major enhancement to /baltop would be for islands to have their own balance where island members/owners can deposit/withdraw money from it. The balance should have its own top (/is baltop) which would outline which island has the biggest bank accounts.

#### Describe the solution you'd like us to implement.

Each island should have a money balance which can be accessed by any member/leader in terms of depositing and withdrawing funds. The balances should be made publically available on a leaderboard such as /is baltop (This would display playerheads similar to /is top)

Suggested commands:
/is balance - displays your islands balance
/is balance {name} - displays the balance of a players island
/is withdraw {amount} - removes {amount} from the island balance and adds it to the player balance
/is deposit {amount} - removes {amount} from the player balance and adds it to the island balance
/is baltop - Shows a leaderboard of islands who have the highest island money balance
/is transactions - Shows a list of deposits and withdrawals for the players island

Admin commands:
/bsbadmin balance {name} - shows the balance of {name}'s island
/bsbadmin take {name} {amount} - removes {amount} from {name}'s island balance
/bsbadmin give {name} {amount} - adds {amount} to {name}'s island balance
/bsbadmin transactions {name} - Shows a list of deposits and withdrawals for {name}'s island

Transactions should be a feature which can be disabled from the config since it requires logging, or maybe a way to limit how many transactions are saved before overwriting the oldest entry.

#### Describe alternatives you've considered.

N/A

**Comment by Tina-King** [comment]
Excellent, thank you!

**Comment by tastybento** [comment]
In progress... https://ci.codemc.io/job/BentoBoxWorld/job/Bank/

**Comment by tastybento** [comment]
Done.
