### ISSUE TITLE
/is bank deposit/withdraw all

### ISSUE THREAD

**Issue by PancakeCatsss** [BentoBoxWorld/Bank#21]
### Is your feature request related to a problem?

Pretty simple request, would be nice to be able to either tab complete your balance or add an "all" variable when you deposit or withdraw so you don't have to type the amount out if you just want to deposit or withdraw everything. 

### Describe the solution you'd like.

Adding /is bank withdraw all and /is bank deposit all

### Describe alternatives you've considered.

Having it tab complete your balance or island balance would do the same thing pretty much.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

### Other

Thanks.

**Comment by tastybento** [comment]
Check out 1.4 on the CI: https://ci.codemc.io/job/BentoBoxWorld/job/Bank/

**Comment by PancakeCatsss** [comment]
Perfect. Thank you.

**Comment by PancakeCatsss** [comment]
Noticed one slight issue, say i have a balance of "43790.85" when I go to tab it via the command it then shows as "43790.85999999999" which leads to the message that it has to be less than 10 digits. Maybe format the double to 1 decimal place?

**Comment by tastybento** [comment]
The joys of double precision! There could be an issue with rounding, e.g. "43790.85999999999" will round to "43790.9" for 1 place, and "43790.86" for two, both of which is larger than the amount you have in your hand. Maybe for depositing I have to round down and do it to 2 decimal places. I'll try that.

**Comment by PancakeCatsss** [comment]
Hi, Just wondering if there is any examples of how to access an Addon such as the Bank (for adding/remove from a players island bank) through the API?

Thanks.

**Comment by amarcais53** [comment]
> The joys of double precision! There could be an issue with rounding, e.g. "43790.85999999999" will round to "43790.9" for 1 place, and "43790.86" for two, both of which is larger than the amount you have in your hand. Maybe for depositing I have to round down and do it to 2 decimal places. I'll try that.

hey is it still on development ? we still have the message for the 10 digits
