### ISSUE TITLE
Placeholder: %Bank_[gamemode]_island_balance_formatted%

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/Bank#9]
Hello,

Can you add a new placeholder → **%Bank_[gamemode]_island_balance_formatted%**

Because when a player has more than 1 M on their bank the number is to high.

Can you please add this great feature like %vault_eco_balance_formatted%

Thank you very much

**Comment by tastybento** [comment]
Can you give me explanation of what you want? Like, what should it show if the player has > 1M in the account?

**Comment by Teyir** [comment]
Yes 1M and more please

**Comment by tastybento** [comment]
Sorry, I still don't understand. Do you mean make quantities show like 1M, 1.4M, 1T, etc.?

**Comment by Teyir** [comment]
Yes absolutely

**Comment by tastybento** [comment]
These are now active. Try the latest SNAPSHOT from https://ci.bentobox.world and let me know if it works for you:

%Bank_[gamemode]_island_balance_formatted%
%Bank_[gamemode]_visited_island_balance_formatted%

**Comment by Teyir** [comment]
Yes thank you very much that work great !

You are very friendly and very efficient
